### ISSUE TITLE
OE schema 설치 문제

### ISSUE THREAD

**Issue by nobandage** [JonghyeokPark/SKKU_DB_2018-2#8]
![screenshot from 2018-10-05 21-30-00](https://user-images.githubusercontent.com/43379742/46566077-267d1400-c953-11e8-9d7f-50740222162d.png)
perl ~ 명령어를 입력할 때 띄어쓰기가 달라지면 bareword found where operator expected at missing operator before~라고 나올 때도 있습니다.
왜 안 되는 걸까요?

**Comment by JonghyeokPark** [comment]
perl -p -i.bak -e 's#__SUB__CWD__#'$(pwd)'#g' *.sql */*.sql */*.dat

올바르게 입력하셨나요?
해당 명령어는 디렉토리 내의 sql파일, dat파일에 있는 경로를 현재 경로로 바꾸어주는 명령어 입니다.
당연히 띄어쓰기는 제대로 되야합니다. 띄어쓰기를 달리하면 명령어는 수행되지 않습니다.
명령어 입력 후, 에러가 발생하지 않는 다면 정상수행된 것입니다. 

또, 스크린샷에서 보이는 것처럼 mksample.sql 명령어 입력할 때 ,tmep 와 $ORACLE_HOME 사이 띄어쓰기가 빠져 있습니다.

**Comment by simon1142** [comment]
![image](https://user-images.githubusercontent.com/43000622/46569312-d5d6dc80-c98d-11e8-90f7-34a624aa55ce.png)
![image](https://user-images.githubusercontent.com/43000622/46569316-df604480-c98d-11e8-8bb3-44b63cf42fb9.png)
![image](https://user-images.githubusercontent.com/43000622/46569318-e6875280-c98d-11e8-8b2b-fdd9072abdda.png)
이번에는 33rows가 뜨는데요;; 설치 중에 위의 오류 비슷한 메세지가 떴었습니다

**Comment by JonghyeokPark** [comment]
첫번째 보여주신 에러 HR 계정이 없는 에러는 스크립트상에서 hr계정을 지웠기 때문에 발생한 것입니다. 
실제 에러가 아닙니다. (스크립트 후반부에 hr계정 새로 만들기 때문에 상관 없습니다.)

이미 로그 파일 디렉토리가 존재해서 발생하는 두번째 "can not create directory" 에러는 무시해도 될 것 같습니다.

사용자마다, row갯수가 다른 것은 정확한 이유는 모르겠지만, view 또는 trigger생성에서 차이가 발생한 것 같습니다. 
아래 테이블만 존재하면 이번 과제를 수행하는데는 큰 문제가 없을 것 같습니다.

![image](https://user-images.githubusercontent.com/7540698/46573477-d9d81e00-c9d0-11e8-8804-d93a7ded0cbc.png)

https://docs.oracle.com/cd/B14117_01/server.101/b10771/scripts004.htm 참고

**Comment by simon1142** [comment]
다 있는데 STYLESHEET_TAB 만 없습니다 ;;;
